using System;
using System.Text;

namespace  SCP_Emu
{
    class SCP_Console
    {
        static public void SCP_Startup_Log()
        {
             Console.WriteLine("User [unspecified] path: \"\"");
                    Console.WriteLine("SCP_Emu Comon Suppliz SCPService emulator version 6.99999.9999 of 57-10-01 [128-bit Unicode]");
                    Console.WriteLine("");
                    Console.WriteLine("Constructing the only Corba_Command_Api_Impl");
                    Console.WriteLine("Import: $TEMPLATE_SYSTEM");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\scp\\system\\control_kinds.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\scp\\system\\control_parameters.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\scp\\system\\control_properties.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\scp\\system\\measure_base.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\scp\\system\\meta_model.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\scp\\system\\model_access.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\scp\\system\\user.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\measure_base.dat	using measure_base");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\measure_base.dat 61 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\model_access.dat	using model_access");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\model_access.dat 14 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\meta_model.dat	using meta_model");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\meta_model.dat 27 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\user.dat	using user");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\user.dat 20 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\control_properties.dat	using control_properties");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\control_properties.dat 198 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\control_kinds.dat	using control_kinds");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\control_kinds.dat 118 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\control_parameters.dat	using control_parameters");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\scp\\system\\control_parameters.dat 20 records");
                    Console.WriteLine("User [unspecified] path: \"C:/i2/scp/6.999/5.2_schema/scp/reports\\scp, C:/i2/scp/6.999/5.2_schema/scp/reports\\scp\\imex, C:/i2/scp/6.999/5.2_schema/scp/reports\\calendar, C:/i2/scp/6.999/5.2_schema/scp/reports\\basic\\english, C:/i2/scp/6.999/5.2_schema/scp/reports\\basic\"");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\reports\\scp\\imex\\define_plim_plex_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\field_set.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\horizon.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\reports\\basic\\default_number.fmt");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\meta_model.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\user.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\vb_models.dat	using meta_model");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\reports\\basic\\default_string.fmt");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\vb_models.dat 752 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\vb_data_models.dat	using meta_model");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\vb_data_models.dat 112 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\field_set.dat	using field_set");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\field_set.dat 15 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\horizon.dat	using horizon");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\horizon.dat 9 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\user.dat	using user");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\user.dat 12 records");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\ip\\meta_model.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\ip\\user.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\ip\\meta_model.dat	using meta_model");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\ip\\meta_model.dat 58 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\ip\\user.dat	using user");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\ip\\user.dat 12 records");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\vb_system\\load_ui_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\cdm_schema_scp_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\load_cdm_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\cdm_entity_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\common_prod\\models\\cdm_date.fmt");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\reports\\basic\\default_date.fmt");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\ope\\op\\functions\\data_quantity.fmt");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\cdm_scp_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\ope_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\lp_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\po_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\map_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\engine_schema_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\create_common_export_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\create_op_export_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\create_ss_export_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\Entity_Model_Mapping.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\entity_model_mapping.dat	using Entity_Model_Mapping");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\entity_model_mapping.dat 44 records");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\oil\\meta\\meta_model.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\oil\\meta\\lp_model.dat	using meta_model");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\oil\\meta\\lp_model.dat 115 records");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\Default_Parameters.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\default_parameters.dat	using Default_Parameters");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\default_parameters.dat 7 records");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\Export_Controls.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\cdm_schema_scp_export_logicals.dat	using Export_Controls");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\cdm_schema_scp_export_logicals.dat 875 records");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\Default_Parameters.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\Entity_Model_Mapping.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\Export_Controls.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\measure_base.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\meta_model.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\measure_base.dat	using measure_base");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\measure_base.dat 13 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\entity_model_mapping.dat	using Entity_Model_Mapping");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\entity_model_mapping.dat 44 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\meta_model.dat	using meta_model");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\meta_model.dat 167 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\cdm_schema_scp_export_logicals.dat	using Export_Controls");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\cdm_schema_scp_export_logicals.dat 875 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\default_parameters.dat	using Default_Parameters");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\5.2_schema\\scp\\models\\default_parameters.dat 7 records");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\oil\\meta\\meta_model.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\oil\\meta\\lp_model.dat	using meta_model");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\oil\\meta\\lp_model.dat 115 records");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\tmapi_template\\functions\\template_scripts\\whylate\\create_late_short_fields.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\tmapi_template\\models\\custom_meta_model.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\tmapi_template\\models\\measure_base.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\tmapi_template\\models\\meta_model.imp");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\tmapi_template\\models\\template_meta_model.imp");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\tmapi_template\\models\\measure_base.dat	using measure_base");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\tmapi_template\\models\\measure_base.dat 17 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\tmapi_template\\models\\meta_model.dat	using meta_model");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\tmapi_template\\models\\meta_model.dat 68 records");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\tmapi_template\\models\\template_meta_model.dat	using template_meta_model");
                    Console.WriteLine("Reading file C:\\i2\\scp\\6.999\\tmapi_template\\models\\template_meta_model.dat 532 records");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\tmapi_template\\functions\\template_scripts\\preprocess\\rbvs_sourcing_class.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\tmapi_template\\functions\\template_scripts\\preprocess\\match_code_models.fws");
                    Console.WriteLine("Reading C:\\i2\\scp\\6.999\\tmapi_template\\functions\\template_scripts\\elops\\time_var_attach_rate_model.fws");
                    Console.WriteLine("Reading corba_interface.def");
                    Console.WriteLine("Handling requests from port 8880");
                    Console.WriteLine("Running main loop");
                    Console.WriteLine("Now corba command api is processing events");
                    Console.WriteLine("===== Creating model for adapter transform_fp");
                    Console.WriteLine("No data imported for transform_fp");
                    Console.WriteLine("CreateModel transform_fp: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for transform_fp ");
                    Console.WriteLine("===== Importing data for post_processing ");
                    Console.WriteLine("Importing data for post_processing : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for post_processing ");
                    Console.WriteLine("===== Importing data for site ");
                    Console.WriteLine("Importing data for site : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for site ");
                    Console.WriteLine("===== Importing data for generic_plan_parameters ");
                    Console.WriteLine("Importing data for generic_plan_parameters : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for generic_plan_parameters ");
                    Console.WriteLine("===== Importing data for plan_parameters ");
                    Console.WriteLine("Importing data for plan_parameters : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for plan_parameters ");
                    Console.WriteLine("===== Importing data for supply_chain ");
                    Console.WriteLine("Importing data for supply_chain : CPU time : 20 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for supply_chain ");
                    Console.WriteLine("===== Importing data for handling ");
                    Console.WriteLine("Importing data for handling : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for handling ");
                    Console.WriteLine("===== Importing data for location ");
                    Console.WriteLine("Importing data for location : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for location ");
                    Console.WriteLine("===== Importing data for lp_layers ");
                    Console.WriteLine("Importing data for lp_layers : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for lp_layers ");
                    Console.WriteLine("===== Creating model for adapter generic_plan_parameters");
                    Console.WriteLine("creating model for generic_plan_parameters with length 4");
                    Console.WriteLine("Created models for generic_plan_parameters");
                    Console.WriteLine("CreateModel generic_plan_parameters: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for generic_plan_parameters ");
                    Console.WriteLine("===== Creating model for adapter plan_parameters");
                    Console.WriteLine("creating model for plan_parameters with length 1");
                    Console.WriteLine("Created models for plan_parameters");
                    Console.WriteLine("CreateModel plan_parameters: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for plan_parameters ");
                    Console.WriteLine("===== Creating model for adapter lp_layers");
                    Console.WriteLine("creating model for lp_layers with length 13");
                    Console.WriteLine("Created models for lp_layers");
                    Console.WriteLine("CreateModel lp_layers: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for lp_layers ");
                    Console.WriteLine("===== Importing data for horizon ");
                    Console.WriteLine("Importing data for horizon : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for horizon ");
                    Console.WriteLine("===== Importing data for plan_objectives ");
                    Console.WriteLine("Importing data for plan_objectives : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for plan_objectives ");
                    Console.WriteLine("===== Importing data for customer_field ");
                    Console.WriteLine("Importing data for customer_field : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for customer_field ");
                    Console.WriteLine("===== Creating model for adapter customer_field");
                    Console.WriteLine("creating model for customer_field with length 65");
                    Console.WriteLine("Created models for customer_field");
                    Console.WriteLine("CreateModel customer_field: CPU time : 211 ms.  Real time : 1000 ms.");
                    Console.WriteLine("===== Finished creating model for customer_field ");
                    Console.WriteLine("===== Creating model for adapter export_udf_field");
                    Console.WriteLine("No data imported for export_udf_field");
                    Console.WriteLine("CreateModel export_udf_field: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for export_udf_field ");
                    Console.WriteLine("===== Creating model for adapter horizon");
                    Console.WriteLine("creating model for horizon with length 1");
                    Console.WriteLine("Created models for horizon");
                    Console.WriteLine("CreateModel horizon: CPU time : 40 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for horizon ");
                    Console.WriteLine("===== Creating model for adapter supply_chain");
                    Console.WriteLine("creating model for supply_chain with length 1");
                    Console.WriteLine("Created models for supply_chain");
                    Console.WriteLine("CreateModel supply_chain: CPU time : 441 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for supply_chain ");
                    Console.WriteLine("===== Creating model for adapter site");
                    Console.WriteLine("creating model for site with length 1");
                    Console.WriteLine("Created models for site");
                    Console.WriteLine("CreateModel site: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for site ");
                    Console.WriteLine("===== Importing data for plan ");
                    Console.WriteLine("Importing data for plan : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for plan ");
                    Console.WriteLine("===== Importing data for intransit_shipment ");
                    Console.WriteLine("Importing data for intransit_shipment : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for intransit_shipment ");
                    Console.WriteLine("===== Importing data for item_group ");
                    Console.WriteLine("Importing data for item_group : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for item_group ");
                    Console.WriteLine("===== Importing data for supplier ");
                    Console.WriteLine("Importing data for supplier : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for supplier ");
                    Console.WriteLine("===== Importing data for on_hand ");
                    Console.WriteLine("Importing data for on_hand : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for on_hand ");
                    Console.WriteLine("===== Importing data for resource ");
                    Console.WriteLine("Importing data for resource : CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for resource ");
                    Console.WriteLine("===== Importing data for item ");
                    Console.WriteLine("Importing data for item : CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for item ");
                    Console.WriteLine("===== Creating model for adapter item");
                    Console.WriteLine("creating model for item with length 423");
                    Console.WriteLine("Created models for item");
                    Console.WriteLine("CreateModel item: CPU time : 30 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item ");
                    Console.WriteLine("===== Importing data for resource_additional ");
                    Console.WriteLine("Importing data for resource_additional : CPU time : 20 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for resource_additional ");
                    Console.WriteLine("===== Importing data for bom ");
                    Console.WriteLine("Importing data for bom : CPU time : 20 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for bom ");
                    Console.WriteLine("===== Importing data for bod ");
                    Console.WriteLine("Importing data for bod : CPU time : 61 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for bod ");
                    Console.WriteLine("===== Importing data for operation ");
                    Console.WriteLine("Importing data for operation : CPU time : 40 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for operation ");
                    Console.WriteLine("===== Importing data for wip ");
                    Console.WriteLine("Importing data for wip : CPU time : 70 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for wip ");
                    Console.WriteLine("===== Importing data for demand ");
                    Console.WriteLine("Importing data for demand : CPU time : 90 ms.  Real time : 1000 ms.");
                    Console.WriteLine("===== Finished importing data for demand ");
                    Console.WriteLine("===== Importing data for product ");
                    Console.WriteLine("Importing data for product : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for product ");
                    Console.WriteLine("===== Appending data for demand ");
                    Console.WriteLine("Importing data for demand : CPU time : 20 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for demand ");
                    Console.WriteLine("===== Importing data for material_buffer ");
                    Console.WriteLine("Importing data for material_buffer : CPU time : 140 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for material_buffer ");
                    Console.WriteLine("===== Importing data for buffer_group ");
                    Console.WriteLine("Importing data for buffer_group : CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for buffer_group ");
                    Console.WriteLine("===== Importing data for calendar ");
                    Console.WriteLine("Importing data for calendar : CPU time : 270 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for calendar ");
                    Console.WriteLine("===== Creating model for adapter calendar");
                    Console.WriteLine("creating model for calendar with length 210");
                    Console.WriteLine("Created models for calendar");
                    Console.WriteLine("CreateModel calendar: CPU time : 1301 ms.  Real time : 1000 ms.");
                    Console.WriteLine("===== Finished creating model for calendar ");
                    Console.WriteLine("===== Creating model for adapter location");
                    Console.WriteLine("creating model for location with length 40");
                    Console.WriteLine("Created models for location");
                    Console.WriteLine("CreateModel location: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for location ");
                    Console.WriteLine("===== Creating model for adapter location_hierarchy");
                    Console.WriteLine("No data imported for location_hierarchy");
                    Console.WriteLine("CreateModel location_hierarchy: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for location_hierarchy ");
                    Console.WriteLine("===== Creating model for adapter handling");
                    Console.WriteLine("creating model for handling with length 14");
                    Console.WriteLine("Created models for handling");
                    Console.WriteLine("CreateModel handling: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for handling ");
                    Console.WriteLine("===== Creating model for adapter storage");
                    Console.WriteLine("No data imported for storage");
                    Console.WriteLine("CreateModel storage: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for storage ");
                    Console.WriteLine("===== Creating model for adapter operation");
                    Console.WriteLine("creating model for operation with length 39");
                    Console.WriteLine("Created models for operation");
                    Console.WriteLine("CreateModel operation: CPU time : 120 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for operation ");
                    Console.WriteLine("===== Creating model for adapter item_pack_detail");
                    Console.WriteLine("No data imported for item_pack_detail");
                    Console.WriteLine("CreateModel item_pack_detail: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item_pack_detail ");
                    Console.WriteLine("===== Creating model for adapter material_buffer");
                    Console.WriteLine("creating model for material_buffer with length 807");
                    Console.WriteLine("Created models for material_buffer");
                    Console.WriteLine("CreateModel material_buffer: CPU time : 321 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for material_buffer ");
                    Console.WriteLine("===== Creating model for adapter item_group");
                    Console.WriteLine("creating model for item_group with length 3");
                    Console.WriteLine("Created models for item_group");
                    Console.WriteLine("CreateModel item_group: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item_group ");
                    Console.WriteLine("===== Creating model for adapter resource");
                    Console.WriteLine("creating model for resource with length 163");
                    Console.WriteLine("Created models for resource");
                    Console.WriteLine("CreateModel resource: CPU time : 110 ms.  Real time : 1000 ms.");
                    Console.WriteLine("===== Finished creating model for resource ");
                    Console.WriteLine("===== Creating model for adapter buffer_group");
                    Console.WriteLine("creating model for buffer_group with length 4");
                    Console.WriteLine("Created models for buffer_group");
                    Console.WriteLine("CreateModel buffer_group: CPU time : 60 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for buffer_group ");
                    Console.WriteLine("===== Creating model for adapter resource_additional");
                    Console.WriteLine("creating model for resource_additional with length 22");
                    Console.WriteLine("Created models for resource_additional");
                    Console.WriteLine("CreateModel resource_additional: CPU time : 70 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for resource_additional ");
                    Console.WriteLine("===== Creating model for adapter inventory_band");
                    Console.WriteLine("No data imported for inventory_band");
                    Console.WriteLine("CreateModel inventory_band: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for inventory_band ");
                    Console.WriteLine("===== Creating model for adapter resource_alternate");
                    Console.WriteLine("No data imported for resource_alternate");
                    Console.WriteLine("CreateModel resource_alternate: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for resource_alternate ");
                    Console.WriteLine("===== Creating model for adapter bom");
                    Console.WriteLine("creating model for bom with length 506");
                    Console.WriteLine("Created models for bom");
                    Console.WriteLine("CreateModel bom: CPU time : 40 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for bom ");
                    Console.WriteLine("===== Creating model for adapter product");
                    Console.WriteLine("creating model for product with length 377");
                    Console.WriteLine("Created models for product");
                    Console.WriteLine("CreateModel product: CPU time : 170 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for product ");
                    Console.WriteLine("===== Creating model for adapter inventory_forecast");
                    Console.WriteLine("No data imported for inventory_forecast");
                    Console.WriteLine("CreateModel inventory_forecast: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for inventory_forecast ");
                    Console.WriteLine("===== Creating model for adapter supplier");
                    Console.WriteLine("creating model for supplier with length 3");
                    Console.WriteLine("Created models for supplier");
                    Console.WriteLine("CreateModel supplier: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for supplier ");
                    Console.WriteLine("===== Creating model for adapter bod");
                    Console.WriteLine("creating model for bod with length 2");
                    Console.WriteLine("Created models for bod");
                    Console.WriteLine("CreateModel bod: CPU time : 120 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for bod ");
                    Console.WriteLine("===== Creating model for adapter sales_bom");
                    Console.WriteLine("No data imported for sales_bom");
                    Console.WriteLine("CreateModel sales_bom: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for sales_bom ");
                    Console.WriteLine("===== Creating model for adapter resource_calendar_other");
                    Console.WriteLine("No data imported for resource_calendar_other");
                    Console.WriteLine("CreateModel resource_calendar_other: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for resource_calendar_other ");
                    Console.WriteLine("===== Creating model for adapter item_substitute");
                    Console.WriteLine("No data imported for item_substitute");
                    Console.WriteLine("CreateModel item_substitute: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item_substitute ");
                    Console.WriteLine("===== Creating model for adapter cto_order");
                    Console.WriteLine("No data imported for cto_order");
                    Console.WriteLine("CreateModel cto_order: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for cto_order ");
                    Console.WriteLine("===== Creating model for adapter plan");
                    Console.WriteLine("creating model for plan with length 1");
                    Console.WriteLine("Created models for plan");
                    Console.WriteLine("CreateModel plan: CPU time : 301 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for plan ");
                    Console.WriteLine("===== Creating model for adapter on_hand");
                    Console.WriteLine("creating model for on_hand with length 108");
                    Console.WriteLine("Created models for wip");
                    Console.WriteLine("CreateModel wip: CPU time : 7190 ms.  Real time : 7000 ms.");
                    Console.WriteLine("===== Finished creating model for wip ");
                    Console.WriteLine("===== Creating model for adapter demand");
                    Console.WriteLine("creating model for demand with length 1467");
                    Console.WriteLine("Created models for demand");
                    Console.WriteLine("CreateModel demand: CPU time : 261 ms.  Real time : 1000 ms.");
                    Console.WriteLine("===== Finished creating model for demand ");
                    Console.WriteLine("===== Creating model for adapter item_seller_price");
                    Console.WriteLine("No data imported for item_seller_price");
                    Console.WriteLine("CreateModel item_seller_price: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item_seller_price ");
                    Console.WriteLine("===== Creating model for adapter sales_product_calendar");
                    Console.WriteLine("No data imported for sales_product_calendar");
                    Console.WriteLine("CreateModel sales_product_calendar: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for sales_product_calendar ");
                    Console.WriteLine("===== Creating model for adapter import_shipment_plan");
                    Console.WriteLine("No data imported for import_shipment_plan");
                    Console.WriteLine("CreateModel import_shipment_plan: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for import_shipment_plan ");
                    Console.WriteLine("===== Creating model for adapter product_mix_entry");
                    Console.WriteLine("No data imported for product_mix_entry");
                    Console.WriteLine("CreateModel product_mix_entry: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for product_mix_entry ");
                    Console.WriteLine("===== Creating model for adapter approved_supplier_price_break");
                    Console.WriteLine("No data imported for approved_supplier_price_break");
                    Console.WriteLine("CreateModel approved_supplier_price_break: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for approved_supplier_price_break ");
                    Console.WriteLine("===== Creating model for adapter post_processing");
                    Console.WriteLine("creating model for post_processing with length 1");
                    Console.WriteLine("Created models for post_processing");
                    Console.WriteLine("CreateModel post_processing: CPU time : 50 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for post_processing ");
                    Console.WriteLine("===== Importing data for post_processing ");
                    Console.WriteLine("Importing data for post_processing : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for post_processing ");
                    Console.WriteLine("===== Creating model for adapter transform_fp");
                    Console.WriteLine("No data imported for transform_fp");
                    Console.WriteLine("CreateModel transform_fp: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for transform_fp ");
                    Console.WriteLine("===== Importing data for generic_plan_parameters ");
                    Console.WriteLine("Importing data for generic_plan_parameters : CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for generic_plan_parameters ");
                    Console.WriteLine("===== Importing data for plan_parameters ");
                    Console.WriteLine("Importing data for plan_parameters : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for plan_parameters ");
                    Console.WriteLine("===== Importing data for site ");
                    Console.WriteLine("Importing data for site : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for site ");
                    Console.WriteLine("===== Importing data for supply_chain ");
                    Console.WriteLine("Importing data for supply_chain : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for supply_chain ");
                    Console.WriteLine("===== Creating model for adapter plan_parameters");
                    Console.WriteLine("creating model for plan_parameters with length 1");
                    Console.WriteLine("Created models for plan_parameters");
                    Console.WriteLine("CreateModel plan_parameters: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for plan_parameters ");
                    Console.WriteLine("===== Creating model for adapter generic_plan_parameters");
                    Console.WriteLine("creating model for generic_plan_parameters with length 4");
                    Console.WriteLine("Created models for generic_plan_parameters");
                    Console.WriteLine("CreateModel generic_plan_parameters: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for generic_plan_parameters ");
                    Console.WriteLine("===== Importing data for location ");
                    Console.WriteLine("Importing data for location : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for location ");
                    Console.WriteLine("===== Importing data for handling ");
                    Console.WriteLine("Importing data for handling : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for handling ");
                    Console.WriteLine("===== Importing data for horizon ");
                    Console.WriteLine("Importing data for horizon : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for horizon ");
                    Console.WriteLine("===== Importing data for lp_layers ");
                    Console.WriteLine("Importing data for lp_layers : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for lp_layers ");
                    Console.WriteLine("===== Creating model for adapter lp_layers");
                    Console.WriteLine("creating model for lp_layers with length 13");
                    Console.WriteLine("Created models for lp_layers");
                    Console.WriteLine("CreateModel lp_layers: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for lp_layers ");
                    Console.WriteLine("===== Importing data for intransit_shipment ");
                    Console.WriteLine("Importing data for intransit_shipment : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for intransit_shipment ");
                    Console.WriteLine("===== Importing data for plan ");
                    Console.WriteLine("Importing data for plan : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for plan ");
                    Console.WriteLine("===== Importing data for customer_field ");
                    Console.WriteLine("Importing data for customer_field : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for customer_field ");
                    Console.WriteLine("===== Importing data for supplier ");
                    Console.WriteLine("Importing data for supplier : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for supplier ");
                    Console.WriteLine("===== Creating model for adapter customer_field");
                    Console.WriteLine("creating model for customer_field with length 65");
                    Console.WriteLine("CreateModel customer_field: CPU time : 881 ms.  Real time : 1000 ms.");
                    Console.WriteLine("===== Finished creating model for customer_field ");
                    Console.WriteLine("===== Creating model for adapter export_udf_field");
                    Console.WriteLine("No data imported for export_udf_field");
                    Console.WriteLine("CreateModel export_udf_field: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for export_udf_field ");
                    Console.WriteLine("===== Creating model for adapter supply_chain");
                    Console.WriteLine("creating model for supply_chain with length 1");
                    Console.WriteLine("Created models for supply_chain");
                    Console.WriteLine("CreateModel supply_chain: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for supply_chain ");
                    Console.WriteLine("===== Creating model for adapter horizon");
                    Console.WriteLine("creating model for horizon with length 1");
                    Console.WriteLine("Warning: horizon LP_HORIZON exists, the new horizon will not be created,");
                    Console.WriteLine("Created models for horizon");
                    Console.WriteLine("CreateModel horizon: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for horizon ");
                    Console.WriteLine("===== Creating model for adapter site");
                    Console.WriteLine("creating model for site with length 1");
                    Console.WriteLine("Created models for site");
                    Console.WriteLine("CreateModel site: CPU time : 30 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for site ");
                    Console.WriteLine("===== Importing data for plan_objectives ");
                    Console.WriteLine("Importing data for plan_objectives : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for plan_objectives ");
                    Console.WriteLine("===== Importing data for item_group ");
                    Console.WriteLine("Importing data for item_group : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for item_group ");
                    Console.WriteLine("===== Importing data for on_hand ");
                    Console.WriteLine("Importing data for on_hand : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for on_hand ");
                    Console.WriteLine("===== Importing data for item ");
                    Console.WriteLine("Importing data for item : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for item ");
                    Console.WriteLine("===== Creating model for adapter item");
                    Console.WriteLine("creating model for item with length 423");
                    Console.WriteLine("Created models for item");
                    Console.WriteLine("CreateModel item: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item ");
                    Console.WriteLine("===== Importing data for bod ");
                    Console.WriteLine("Importing data for bod : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for bod ");
                    Console.WriteLine("===== Importing data for resource ");
                    Console.WriteLine("Importing data for resource : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for resource ");
                    Console.WriteLine("===== Importing data for resource_additional ");
                    Console.WriteLine("Importing data for resource_additional : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for resource_additional ");
                    Console.WriteLine("===== Importing data for bom ");
                    Console.WriteLine("Importing data for bom : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for bom ");
                    Console.WriteLine("===== Importing data for wip ");
                    Console.WriteLine("Importing data for wip : CPU time : 20 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for wip ");
                    Console.WriteLine("===== Importing data for operation ");
                    Console.WriteLine("Importing data for operation : CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for operation ");
                    Console.WriteLine("===== Importing data for demand ");
                    Console.WriteLine("Importing data for demand : CPU time : 20 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for demand ");
                    Console.WriteLine("===== Importing data for product ");
                    Console.WriteLine("Importing data for product : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for product ");
                    Console.WriteLine("===== Appending data for demand ");
                    Console.WriteLine("Importing data for demand : CPU time : 90 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for demand ");
                    Console.WriteLine("===== Importing data for material_buffer ");
                    Console.WriteLine("Importing data for material_buffer : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for material_buffer ");
                    Console.WriteLine("===== Importing data for buffer_group ");
                    Console.WriteLine("Importing data for buffer_group : CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for buffer_group ");
                    Console.WriteLine("===== Importing data for calendar ");
                    Console.WriteLine("Importing data for calendar : CPU time : 270 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished importing data for calendar ");
                    Console.WriteLine("===== Creating model for adapter calendar");
                    Console.WriteLine("creating model for calendar with length 210");
                    Console.WriteLine("Created models for calendar");
                    Console.WriteLine("CreateModel calendar: CPU time : 240 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for calendar ");
                    Console.WriteLine("===== Creating model for adapter location");
                    Console.WriteLine("creating model for location with length 40");
                    Console.WriteLine("Created models for location");
                    Console.WriteLine("CreateModel location: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for location ");
                    Console.WriteLine("===== Creating model for adapter location_hierarchy");
                    Console.WriteLine("No data imported for location_hierarchy");
                    Console.WriteLine("CreateModel location_hierarchy: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for location_hierarchy ");
                    Console.WriteLine("===== Creating model for adapter operation");
                    Console.WriteLine("creating model for operation with length 39");
                    Console.WriteLine("Created models for operation");
                    Console.WriteLine("CreateModel operation: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for operation ");
                    Console.WriteLine("===== Creating model for adapter item_group");
                    Console.WriteLine("creating model for item_group with length 3");
                    Console.WriteLine("Created models for item_group");
                    Console.WriteLine("CreateModel item_group: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item_group ");
                    Console.WriteLine("===== Creating model for adapter storage");
                    Console.WriteLine("No data imported for storage");
                    Console.WriteLine("CreateModel storage: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for storage ");
                    Console.WriteLine("===== Creating model for adapter item_pack_detail");
                    Console.WriteLine("No data imported for item_pack_detail");
                    Console.WriteLine("CreateModel item_pack_detail: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item_pack_detail ");
                    Console.WriteLine("===== Creating model for adapter handling");
                    Console.WriteLine("creating model for handling with length 14");
                    Console.WriteLine("Created models for handling");
                    Console.WriteLine("CreateModel handling: CPU time : 10 ms.  Real time : 1000 ms.");
                    Console.WriteLine("===== Finished creating model for handling ");
                    Console.WriteLine("===== Creating model for adapter material_buffer");
                    Console.WriteLine("creating model for material_buffer with length 807");
                    Console.WriteLine("===== Creating model for adapter resource");
                    Console.WriteLine("creating model for resource with length 163");
                    Console.WriteLine("Created models for resource");
                    Console.WriteLine("CreateModel resource: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for resource ");
                    Console.WriteLine("===== Creating model for adapter resource_additional");
                    Console.WriteLine("creating model for resource_additional with length 22");
                    Console.WriteLine("Created models for resource_additional");
                    Console.WriteLine("CreateModel resource_additional: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for resource_additional ");
                    Console.WriteLine("===== Creating model for adapter resource_alternate");
                    Console.WriteLine("No data imported for resource_alternate");
                    Console.WriteLine("CreateModel resource_alternate: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for resource_alternate ");
                    Console.WriteLine("===== Creating model for adapter bom");
                    Console.WriteLine("creating model for bom with length 506");
                    Console.WriteLine("===== Creating model for adapter inventory_forecast");
                    Console.WriteLine("No data imported for inventory_forecast");
                    Console.WriteLine("CreateModel inventory_forecast: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for inventory_forecast ");
                    Console.WriteLine("===== Creating model for adapter supplier");
                    Console.WriteLine("creating model for supplier with length 3");
                    Console.WriteLine("Created models for supplier");
                    Console.WriteLine("CreateModel supplier: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for supplier ");
                    Console.WriteLine("===== Creating model for adapter bod");
                    Console.WriteLine("creating model for bod with length 2");
                    Console.WriteLine("Created models for bod");
                    Console.WriteLine("CreateModel bod: CPU time : 100 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for bod ");
                    Console.WriteLine("===== Creating model for adapter item_substitute");
                    Console.WriteLine("No data imported for item_substitute");
                    Console.WriteLine("CreateModel item_substitute: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item_substitute ");
                    Console.WriteLine("===== Creating model for adapter cto_order");
                    Console.WriteLine("No data imported for cto_order");
                    Console.WriteLine("CreateModel cto_order: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for cto_order ");
                    Console.WriteLine("===== Creating model for adapter resource_calendar_other");
                    Console.WriteLine("No data imported for resource_calendar_other");
                    Console.WriteLine("CreateModel resource_calendar_other: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for resource_calendar_other ");
                    Console.WriteLine("===== Creating model for adapter sales_bom");
                    Console.WriteLine("No data imported for sales_bom");
                    Console.WriteLine("CreateModel sales_bom: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for sales_bom ");
                    Console.WriteLine("===== Creating model for adapter plan");
                    Console.WriteLine("creating model for plan with length 1");
                    Console.WriteLine("Created models for plan");
                    Console.WriteLine("CreateModel plan: CPU time : 130 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for plan ");
                    Console.WriteLine("===== Creating model for adapter on_hand");
                    Console.WriteLine("creating model for on_hand with length 108");
                    Console.WriteLine("Created models for on_hand");
                    Console.WriteLine("CreateModel on_hand: CPU time : 90 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for on_hand ");
                    Console.WriteLine("===== Creating model for adapter ibr_mapping");
                    Console.WriteLine("No data imported for ibr_mapping");
                    Console.WriteLine("CreateModel ibr_mapping: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for ibr_mapping ");
                    Console.WriteLine("===== Creating model for adapter intransit_shipment");
                    Console.WriteLine("creating model for intransit_shipment with length 6");
                    Console.WriteLine("Created models for intransit_shipment");
                    Console.WriteLine("CreateModel intransit_shipment: CPU time : 91 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for intransit_shipment ");
                    Console.WriteLine("===== Creating model for adapter plan_objectives");
                    Console.WriteLine("creating model for plan_objectives with length 39");
                    Console.WriteLine("Created models for plan_objectives");
                    Console.WriteLine("CreateModel plan_objectives: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for plan_objectives ");
                    Console.WriteLine("===== Creating model for adapter wip");
                    Console.WriteLine("creating model for wip with length 468");
                    Console.WriteLine("Created models for wip");
                    Console.WriteLine("CreateModel wip: CPU time : 20 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for wip ");
                    Console.WriteLine("===== Creating model for adapter approved_shipment");
                    Console.WriteLine("No data imported for approved_shipment");
                    Console.WriteLine("CreateModel approved_shipment: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for approved_shipment ");
                    Console.WriteLine("===== Creating model for adapter scheduled_receipt");
                    Console.WriteLine("No data imported for scheduled_receipt");
                    Console.WriteLine("CreateModel scheduled_receipt: CPU time : 10 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for scheduled_receipt ");
                    Console.WriteLine("===== Creating model for adapter demand");
                    Console.WriteLine("creating model for demand with length 1467");
                    Console.WriteLine("===== Creating model for adapter item_seller_price");
                    Console.WriteLine("No data imported for item_seller_price");
                    Console.WriteLine("CreateModel item_seller_price: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for item_seller_price ");
                    Console.WriteLine("===== Creating model for adapter sales_product_calendar");
                    Console.WriteLine("No data imported for sales_product_calendar");
                    Console.WriteLine("CreateModel sales_product_calendar: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for sales_product_calendar ");
                    Console.WriteLine("===== Creating model for adapter import_shipment_plan");
                    Console.WriteLine("No data imported for import_shipment_plan");
                    Console.WriteLine("CreateModel import_shipment_plan: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for import_shipment_plan ");
                    Console.WriteLine("===== Creating model for adapter product_mix_entry");
                    Console.WriteLine("No data imported for product_mix_entry");
                    Console.WriteLine("CreateModel product_mix_entry: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for product_mix_entry ");
                    Console.WriteLine("===== Creating model for adapter approved_supplier_price_break");
                    Console.WriteLine("No data imported for approved_supplier_price_break");
                    Console.WriteLine("CreateModel approved_supplier_price_break: CPU time : 0 ms.  Real time : 0 ms.");
                    Console.WriteLine("===== Finished creating model for approved_supplier_price_break ");
                    Console.WriteLine("===== Creating model for adapter post_processing");
                    Console.WriteLine("creating model for post_processing with length 1");
                    Console.WriteLine("Created models for post_processing");
                    Console.WriteLine("CreateModel post_processing: CPU time : 131 ms.  Real time : 1000 ms.");
                    Console.WriteLine("===== Finished creating model for post_processing ");
                    Console.WriteLine("[Thread 2364] Finished [Command: eval_expression for [TCP_Server_Channel: 8, User: hideoyon], 0% done P4]");

        }
    }
}
